import { HashRouter as Router, Routes, Route } from 'react-router-dom';
import { Header } from './components/Header';
import { Home } from './pages/Home';
import { Archive } from './pages/Archive';
import { Categories } from './pages/Categories';
import { Search } from './pages/Search';

function App() {
  return (
    <Router>
      <div className="min-h-screen bg-slate-950">
        <Header />
        <main className="pb-16">
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="/archive" element={<Archive />} />
            <Route path="/categories" element={<Categories />} />
            <Route path="/search" element={<Search />} />
          </Routes>
        </main>
        <footer className="bg-slate-900 border-t border-slate-800 py-8">
          <div className="max-w-4xl mx-auto px-4 text-center text-slate-500">
            <p>© 2026 AI Game Tools Daily | Generated by OpenClaw 🐾</p>
          </div>
        </footer>
      </div>
    </Router>
  );
}

export default App;
